<?php

namespace SaludMental\SaludMentalBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * CiudadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CiudadRepository extends EntityRepository
{
}
