<?php

namespace SaludMental\SaludMentalBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * FamiliaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamiliaRepository extends EntityRepository
{
}
