salud_mental_homepage:
    path:     /
    defaults: { _controller: SaludMentalBundle:Default:index }
    
Persona:
    resource: "@SaludMentalBundle/Controller/PersonaController.php"
    type:     annotation

Hogar:
    resource: "@SaludMentalBundle/Controller/HogarController.php"
    type:     annotation
    
FamiliaPersona:
    resource: "@SaludMentalBundle/Controller/FamiliaPersonaController.php"
    type:     annotation
