services:
    sg_datatables.familia:
        class: SaludMental\SaludMentalBundle\Datatables\FamiliaDatatable
        tags:
            - { name: sg.datatable.view }
            
    sg_datatables.persona.new.list:
        class: SaludMental\SaludMentalBundle\Datatables\PersonaNewListDatatable
        tags:
            - { name: sg.datatable.view }
